In [11]:
import numpy as np
arr1=np.array([1,2,3],dtype=int)

In [12]:
arr1

array([1, 2, 3])

In [13]:
arr2=np.array([1,2,3],dtype=float)

In [14]:
arr2

array([1., 2., 3.])

In [32]:
#1d
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1.shape)
print(arr1.ndim)
#2d
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr1.shape)
print(arr1.ndim)
#3d
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,1,3)
print(arr1.shape)
print(arr1.ndim)

#4d
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,1,3,1)
print(arr1.shape)
print(arr1.ndim)
                
    
#0d
arr1=np.array(4)
print(arr1.shape)
print(arr1.ndim)

(9,)
1
(3, 3)
2
(3, 1, 3)
3
(3, 1, 3, 1)
4
()
0


arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [15]:
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,1,3
                                          )

In [16]:
arr1

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [33]:
#2x2 , 3x3 and 4X4 identy array
x=np.eye(2)
x=np.eye(3)
x=np.eye(4)

In [ ]:
x=np.eye(3)

In [34]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#zero array of 2X5
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
#array of 5 with all element s as 5
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [41]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [43]:
#creating random numbers between 0 to 100 with sample size of 25
np.random.randint(0,100,25)

array([91, 95, 21, 99, 94, 74, 45, 27, 14, 11, 15, 54, 22,  8, 82, 45, 22,
        2, 20, 31, 66, 57,  7, 45, 53])

In [44]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
#random numbers of size 2X3 within 0 to 100 and reshape to 3X2
np.random.randint(0,100,size=(2,3)).reshape(3,2)

array([[ 8, 71],
       [18, 77],
       [25, 36]])

In [47]:
arr1=np.random.randint(0,1000,50)

In [52]:
arr1

array([888, 458, 891,  96, 159, 693, 239, 384, 623,  78, 869, 362, 415,
        79, 248, 287, 987, 530, 675, 439, 998, 155, 968,  18, 877, 625,
       895, 371, 697, 706, 159, 606,  70,  49,  33, 413, 800,  75, 628,
       349, 906, 662, 217, 936, 834, 865, 710, 299, 996, 394])

In [ ]:
1) arr1=np.random.randint(0,1001,50)
2)arr1[0:10]
3)arr1[:-11:-1]
4)arr1[10:26]
5)arr1[22]
6)arr1[:-11:-1]

In [48]:
arr1[0:10]

array([888, 458, 891,  96, 159, 693, 239, 384, 623,  78])

In [53]:
arr1[:-11:-1]

array([394, 996, 299, 710, 865, 834, 936, 217, 662, 906])

In [54]:
arr1[10:26]

array([869, 362, 415,  79, 248, 287, 987, 530, 675, 439, 998, 155, 968,
        18, 877, 625])

In [55]:
arr1[22]

968

In [ ]:
arr1[:-11:-1]

In [61]:
arr1=np.array([1,2,3,4,5])

np.insert(arr1,len(arr1),6)
np.insert(arr1,0,6)

array([6, 1, 2, 3, 4, 5])

In [63]:
print(np.where(arr1==4))

(array([3], dtype=int64),)


In [65]:
np.indexOf(4)

AttributeError: module 'numpy' has no attribute 'indexOf'

In [67]:
np.insert(arr1,(np.where(arr1==4))[0],30)

array([ 1,  2,  3, 30,  4,  5])

In [69]:
np.where(arr1==5,50,arr1)

array([ 1,  2,  3,  4, 50])

In [70]:
#deleting 50
np.delete(arr1,4)

array([1, 2, 3, 4])

In [71]:
def search(num):
    for i in arr1:
        if(i==num):
            return True
    return False

In [72]:
search(30)

False

In [73]:
np.sort(arr1)

array([1, 2, 3, 4, 5])

In [76]:
np.sort?