In [1]:
# gives the binary format
bin(10)

'0b1010'

In [2]:
#id gives the memory address of the variablenu
a=10
print(a,id(a))

10 140714613118024


In [3]:
num=10
print(num,id(num))
num=20
print(num,id(num))

10 140714613118024
20 140714613118344


In [5]:
#memory management using python

#same memory for a data defined this is called "interning"
num=10
print(num,id(num))
copy=10
print(copy,id(copy))


#this reusng the memory happens till 256 and -5
num=257
print(num,id(num))
copy=257
print(copy,id(copy))

10 140714613118024
10 140714613118024
257 2316310777776
257 2316310786928


In [7]:
# to reuse the memory after the range we use sys
import sys
num=sys.intern('257')
print(num,id(num))
copy=sys.intern('257')
print(copy,id(copy))


257 2316311967856
257 2316311967856


In [8]:
#short circuiting
age=21
age= age>18 and 'eligible'

In [9]:
age

'eligible'

In [10]:
print(~0)

-1


In [11]:
print(~1)

-2


In [12]:
print(~-2)

1


In [14]:
print("Hello","guys",sep="! ")

Hello! guys


In [15]:
#is vs ==

num1=1000
num2=1000

print(num1==num2)

True


In [16]:
print(num1 is num2)
#false because after 256 the number start sharing the same memory

False


In [17]:
name="ani"

print(f"my name is {name}")

my name is ani


In [19]:
print?

In [20]:
name.lower()

'ani'

In [21]:
name.upper()

'ANI'

In [22]:
name.capitalize()

'Ani'

In [23]:
n2="   hell "
n2.strip()

'hell'

In [24]:
name.replace('a','k')
#strings are immutable still it changes because new memory is created

'kni'

In [25]:
n1="Hello,my,name,is,anirudh"
n1.split(",")

['Hello', 'my', 'name', 'is', 'anirudh']

In [26]:
print(name[::-1])

ina


In [27]:
lst=[1,2,3]
lst.pop()

3

In [28]:
lst.index(1)

0

In [29]:
lst.sort()

In [30]:
lst

[1, 2]

In [31]:
lst=[1,22,4]
lst.sort()

In [32]:
lst

[1, 4, 22]

In [33]:
print(lst[::-1])

[22, 4, 1]


In [34]:
lst.remove(4)

In [35]:
lst

[1, 22]

In [36]:
lst.insert(1,45)

In [37]:
lst

[1, 45, 22]

In [40]:
lst[::-1]
#creates a new memory

[22, 45, 1]

In [41]:
lst

[1, 45, 22]

In [42]:
lst.reverse()

In [43]:
lst

[22, 45, 1]

In [44]:
#descending order
lst.sort(reverse=True)

In [45]:
lst

[45, 22, 1]

In [50]:
l1=['ani','Hle','Ani']
l1.sort(key=str.lower)

In [51]:
l1

['ani', 'Ani', 'Hle']

In [52]:
lst.count(1)

1

In [54]:
t1=(1,2,3,4)

In [55]:
len(t1)

4

In [56]:
t1.count(1)

1

In [59]:
s1={1,2,3}

#

In [60]:
s1.add(5)

In [61]:
s1

{1, 2, 3, 5}

In [63]:
s1.discard(7)

# 

In [64]:
s2={1,2,3}


In [65]:
s1.union(s2)

{1, 2, 3, 5}

In [67]:
s1.intersection(s2)

{1, 2, 3}

In [68]:
s1.issubset(s2)

False

In [69]:
s2.issubset(s1)

True

In [74]:
has={0:2}
for i in range(0,10):
    has[i]=1+has.get(i,0)
    

In [75]:
has

{0: 3, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}

In [78]:
for i,k in has.items():
    print(i,k)

0 3
1 1
2 1
3 1
4 1
5 1
6 1
7 1
8 1
9 1


In [82]:
for i in has:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [83]:
l1=['name','age']
l2=['ani',20]

for i,k in zip(l1,l2):
    print(i,k)

name ani
age 20


In [84]:
def func(ls):
    for i in ls:
        print(i)
func([1,2,3,4])

1
2
3
4


In [91]:
#*args
def func(*ls):
    print(*ls)
func((1,2,3,4))

(1, 2, 3, 4)


In [95]:
func= lambda x:[i for i in x if i%2==0]
func([1,2,3,4])

[2, 4]

In [100]:
#use of *args (we use it when the number of input is not known)

def square(side):
    return (side*side)
def rectangle(length,breadth):
    return (length*breadth)
    
def area(shape,*args):
    print(shape(*args))
area(rectangle,5,10)

50


In [102]:
#if i want to print both key value pairs together then

# so giving 11 will start from index number 11
for i,k in enumerate(l1,11):
    print(i,k)

11 name
12 age


In [ ]:
#3 types of programming
# 1) procedural
# 2)functional
# 3)oops



In [106]:
num=10
#gives all the list of magic methods
dir(num)

#this is one of the magic method which runs behind <
num.__lt__(5)



False

In [115]:
class Item:
    def __init__(self,name,price,quantity):
        #assert is used to invoke custom error
        assert price>=0, f"{price} must be greater than 0"
        self.name=name
        self.price=price
        self.quantity=quantity
iphone=Item('14 pro',85000,1)

#backcase is not for all objects hence will define for that only
iphone.backcase=True

#inside th class only generic property must be defined
Tomato=Item('Tomato',20,15)

#dict gives all the the data defined
iphone.__dict__
Tomato.__dict__

{'name': 'Tomato', 'price': 20, 'quantity': 15}

In [116]:
# class variables must be invoked this way
class Item:
    discount=0.2
    def __init__(self,name,price,quantity):
        #assert is used to invoke custom error
        assert price>=0, f"{price} must be greater than 0"
        self.name=name
        self.price=price-price*Item.discount
        self.quantity=quantity
        
iphone=Item('14 pro',85000,1)


In [117]:
iphone.__dict__

{'name': '14 pro', 'price': 68000.0, 'quantity': 1}

In [123]:
#OOPS

class ATM:
    o_username="om"
    o_password="12345"
    
    def __init__(self,username,password):
        self.username=username
        self.password=password
    def validate(self):
        if(ATM.o_username==self.username and ATM.o_password==self.password):
            return True
        return False

ani=ATM("ani","1234")
ani.__dict__
# ani.validate()
#hence need to do encapsulation
print(ani.o_username)
    
    

om


In [134]:
class ATM:
    #made it protected
    #this is valid for all objects
    __o_username="om"
    __o_password="12345"
    
    def __init__(self,username,password):
        self.username=username
        self.password=password
    def validate(self):
        if(ATM.__o_username==self.username and ATM.__o_password==self.password):
            return True
        return False
    
    def getter(self):
        if(self.validate()):
            return ATM.__o_username
    def setter(self,newuser):
        if(self.validate()):
            ATM.__o_username=newuser  

ani=ATM("om","12345")
ani.__dict__
# ani.validate()
#hence need to do encapsulation
#hence cannot be accessed
# print(ani.__o_username)

ani.getter()
ani.setter('ani')
ani.getter()

In [139]:
#single level
class Father:
    def __init__(self):
        self.name="Father"
    def display(self):
        print("Father")
class Child(Father):
    def __init__(self,age):
        super().__init__()
        self.age=age

c1=Child(15)
c1.name
    
    

'Father'

In [140]:
#multiple inheritance (the first written will be taken)
class Father:
    def __init__(self):
        self.name="Father"
    def display(self):
        print("Father")
class Mother:
    def __init__(self):
        self.name="Mother"
    def display(self):
        print("Mother")
class Child(Mother,Father):
    def __init__(self,age):
        super().__init__()
        self.age=age

c1=Child(15)
c1.name
    
    

'Mother'

In [144]:
#abstraction
from abc import ABC,abstractmethod

In [148]:
class Area(ABC):
    @abstractmethod
    def area(self):
        pass
class Square(Area):
    def area(self,side):
        print(side*side)

s1=Square()

In [149]:
s1.area(12)

144


In [151]:
li1=[1,2,3,4]

li1*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [152]:
# now to multiply in list is too difficult

# to make it easy
import numpy as np

In [153]:
n1=np.array(li1)

In [154]:
n1

array([1, 2, 3, 4])

In [155]:
n1*2 #multiplies by 2

array([2, 4, 6, 8])

In [161]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [166]:
np.ones((1,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [167]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [172]:
#diagonal marix of 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [173]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [175]:
np.random.randint(1,10,size=(4,4))

array([[3, 1, 5, 8],
       [6, 8, 3, 4],
       [5, 1, 1, 1],
       [5, 9, 7, 2]])

In [176]:
np.linspace(0,50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [177]:
n1=np.random.randint(1,10,size=(3,3))

In [178]:
n2=np.random.randint(1,10,size=(3,3))

In [179]:
n1+n2

array([[ 6, 10, 14],
       [16,  7,  3],
       [ 9,  4,  9]])

In [180]:
np.log2(5)

2.321928094887362

In [183]:
np.min(n1,axis=1)

array([1, 1, 1])

In [190]:
n1[0:2,0:3]

array([[1, 7, 7],
       [7, 1, 1]])

In [192]:
n1

array([[1, 7, 7],
       [7, 1, 1],
       [3, 1, 7]])

In [193]:
n1>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [195]:
n1[n1>5]

array([7, 7, 7, 7])

In [196]:
np.vstack((n1,n2))

array([[1, 7, 7],
       [7, 1, 1],
       [3, 1, 7],
       [5, 3, 7],
       [9, 6, 2],
       [6, 3, 2]])

In [197]:
np.hstack((n1,n2))

array([[1, 7, 7, 5, 3, 7],
       [7, 1, 1, 9, 6, 2],
       [3, 1, 7, 6, 3, 2]])

In [202]:
np.concatenate((n1,n2),axis=1)

array([[1, 7, 7, 5, 3, 7],
       [7, 1, 1, 9, 6, 2],
       [3, 1, 7, 6, 3, 2]])

In [204]:
n1.shape

(3, 3)

In [205]:
n1.size

9

In [210]:
n1.T

array([[1, 7, 3],
       [7, 1, 1],
       [7, 1, 7]])

In [212]:
import pandas as pd

In [213]:
df=pd.read_csv('market_fact.csv')

In [214]:
df.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [216]:
df.shape

(8399, 10)

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Ord_id               8399 non-null   object 
 1   Prod_id              8399 non-null   object 
 2   Ship_id              8399 non-null   object 
 3   Cust_id              8399 non-null   object 
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64  
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB


In [218]:
df.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin  
count          8336.000000  
mean              0.512513  
std               0.135589  
min               0.350000  
25%               0.380000  
50%               0.520000  
75%               0.590000  
max               0.850000

In [219]:
df[0:100]

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0   Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1   Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2   Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3   Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4   Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
..       ...      ...       ...        ...        ...       ...   
95  Ord_5462   Prod_4  SHP_7632  Cust_1820   175.8565      0.03   
96  Ord_5489  Prod_17  SHP_7671  Cust_1820   754.9200      0.00   
97  Ord_5462   Prod_5  SHP_7631  Cust_1820   323.9600      0.07   
98  Ord_5481  Prod_15  SHP_7659  Cust_1820  2700.7800      0.06   
99  Ord_1638   Prod_5  SHP_5892  Cust_1433   755.1900      0.00   

    Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0               23   -30.51           3.60                 0.56  
1               13     4.56           0.93                 0.54  
2               26  1148.90           2.50                 0.59  
3               43   729.34          14.30                 0.37  
4               35  1219.87          26.30                 0.38  
..             ...      ...            ...                  ...  
95              10   -93.26           1.25                 0.83  
96               7  -129.57          19.99                 0.52  
97              40  -136.82           7.96                 0.49  
98              29  -793.36          58.20                 0.58  
99              41    81.44           8.99                 0.47  

[100 rows x 10 columns]

In [220]:
#diadvantage of normal indexing

# 1) cannot select single row
df[0]

KeyError: 0

In [221]:
# 2)cannot select cutom rows and cols
df[[0,4]]

KeyError: "None of [Index([0, 4], dtype='int32')] are in the [columns]"

In [222]:
#cannot select row and col simentenously

df[100:400,10]

InvalidIndexError: (slice(100, 400, None), 10)

In [223]:
df.iloc[100:400,1]

100     Prod_8
101     Prod_7
102     Prod_2
103    Prod_13
104     Prod_8
        ...   
395     Prod_2
396     Prod_1
397    Prod_11
398     Prod_6
399     Prod_9
Name: Prod_id, Length: 300, dtype: object

In [224]:
df.loc[0:500,['Ord_id']]

Ord_id
0    Ord_5446
1    Ord_5406
2    Ord_5446
3    Ord_5456
4    Ord_5485
..        ...
496  Ord_5310
497  Ord_5272
498  Ord_5257
499  Ord_5309
500  Ord_1127

[501 rows x 1 columns]

In [225]:
df['Discount']>0.2

0       False
1       False
2       False
3       False
4       False
        ...  
8394    False
8395    False
8396    False
8397    False
8398    False
Name: Discount, Length: 8399, dtype: bool

In [226]:
df[df['Discount']>0.2]

Ord_id  Prod_id  Ship_id  Cust_id    Sales  Discount  Order_Quantity  \
7705  Ord_162   Prod_5  SHP_219  Cust_42  338.520      0.21              22   
7713   Ord_13  Prod_11   SHP_17  Cust_12  663.784      0.25              11   

      Profit  Shipping_Cost  Product_Base_Margin  
7705  -17.75           8.99                 0.39  
7713 -481.04          69.00                 0.68

In [228]:
#condition with rwo and col selection
df.loc[df['Discount']>0.2,['Sales']]

Sales
7705  338.520
7713  663.784

In [229]:
df['Discount'].sum()

417.19

In [230]:
df['Discount'].max()

0.25

In [232]:
df.sort_values('Discount',ascending=False)

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
7713    Ord_13  Prod_11    SHP_17    Cust_12   663.784      0.25   
7705   Ord_162   Prod_5   SHP_219    Cust_42   338.520      0.21   
5334   Ord_916   Prod_5  SHP_1262   Cust_328    27.960      0.17   
5326   Ord_960   Prod_5  SHP_1329   Cust_349   651.900      0.16   
5329   Ord_876   Prod_5  SHP_1204   Cust_299   586.110      0.11   
...        ...      ...       ...        ...       ...       ...   
3904  Ord_2920  Prod_15  SHP_4032  Cust_1055  1004.890      0.00   
3899  Ord_4575   Prod_6  SHP_6366  Cust_1514   231.650      0.00   
3897  Ord_4411   Prod_1  SHP_6147  Cust_1514  3644.240      0.00   
3879   Ord_236   Prod_7   SHP_329   Cust_104    68.140      0.00   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.690      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
7713              11 -481.04          69.00                 0.68  
7705              22  -17.75           8.99                 0.39  
5334               1   -9.13          13.56                 0.58  
5326              49  -74.51           6.85                 0.54  
5329              43   98.44           4.98                 0.48  
...              ...     ...            ...                  ...  
3904              10 -189.02          42.00                 0.66  
3899              37 -241.28          10.39                 0.40  
3897              33 -457.73          35.00                 0.82  
3879              30    6.37           0.78                 0.52  
8398              47  131.39           4.86                 0.38  

[8399 rows x 10 columns]

df['Prod_id'].unique()

In [233]:
df['Prod_id'].unique()

array(['Prod_16', 'Prod_13', 'Prod_4', 'Prod_6', 'Prod_17', 'Prod_12',
       'Prod_2', 'Prod_11', 'Prod_10', 'Prod_5', 'Prod_9', 'Prod_15',
       'Prod_7', 'Prod_3', 'Prod_1', 'Prod_8', 'Prod_14'], dtype=object)

In [234]:
df['Prod_id'].value_counts()

Prod_id
Prod_6     1225
Prod_3      915
Prod_4      883
Prod_5      788
Prod_8      758
Prod_13     633
Prod_1      546
Prod_2      434
Prod_15     386
Prod_11     361
Prod_17     337
Prod_12     288
Prod_9      246
Prod_10     189
Prod_7      179
Prod_16     144
Prod_14      87
Name: count, dtype: int64

In [236]:
g1=df.groupby('Prod_id')

In [238]:
g1['Profit'].sum()

Prod_id
Prod_1       6664.15
Prod_10    -33582.13
Prod_11    -99062.50
Prod_12     13677.17
Prod_13      7564.78
Prod_14    167361.49
Prod_15    149649.73
Prod_16     -7799.25
Prod_17    307712.93
Prod_2      97158.06
Prod_3     307413.39
Prod_4     316951.62
Prod_5     100427.93
Prod_6      45263.20
Prod_7       -102.67
Prod_8      94287.48
Prod_9      48182.60
Name: Profit, dtype: float64

In [243]:
g1[['Prod_id','Ship_id']].sum()

Prod_id  \
Prod_id                                                      
Prod_1   Prod_1Prod_1Prod_1Prod_1Prod_1Prod_1Prod_1Prod...   
Prod_10  Prod_10Prod_10Prod_10Prod_10Prod_10Prod_10Prod...   
Prod_11  Prod_11Prod_11Prod_11Prod_11Prod_11Prod_11Prod...   
Prod_12  Prod_12Prod_12Prod_12Prod_12Prod_12Prod_12Prod...   
Prod_13  Prod_13Prod_13Prod_13Prod_13Prod_13Prod_13Prod...   
Prod_14  Prod_14Prod_14Prod_14Prod_14Prod_14Prod_14Prod...   
Prod_15  Prod_15Prod_15Prod_15Prod_15Prod_15Prod_15Prod...   
Prod_16  Prod_16Prod_16Prod_16Prod_16Prod_16Prod_16Prod...   
Prod_17  Prod_17Prod_17Prod_17Prod_17Prod_17Prod_17Prod...   
Prod_2   Prod_2Prod_2Prod_2Prod_2Prod_2Prod_2Prod_2Prod...   
Prod_3   Prod_3Prod_3Prod_3Prod_3Prod_3Prod_3Prod_3Prod...   
Prod_4   Prod_4Prod_4Prod_4Prod_4Prod_4Prod_4Prod_4Prod...   
Prod_5   Prod_5Prod_5Prod_5Prod_5Prod_5Prod_5Prod_5Prod...   
Prod_6   Prod_6Prod_6Prod_6Prod_6Prod_6Prod_6Prod_6Prod...   
Prod_7   Prod_7Prod_7Prod_7Prod_7Prod_7Prod_7Prod_7Prod...   
Prod_8   Prod_8Prod_8Prod_8Prod_8Prod_8Prod_8Prod_8Prod...   
Prod_9   Prod_9Prod_9Prod_9Prod_9Prod_9Prod_9Prod_9Prod...   

                                                   Ship_id  
Prod_id                                                     
Prod_1   SHP_1634SHP_6327SHP_7481SHP_286SHP_1895SHP_225...  
Prod_10  SHP_3006SHP_3256SHP_2098SHP_3025SHP_7451SHP_76...  
Prod_11  SHP_3093SHP_1635SHP_6079SHP_3211SHP_3255SHP_72...  
Prod_12  SHP_41SHP_3395SHP_7025SHP_6650SHP_6437SHP_6335...  
Prod_13  SHP_7549SHP_6593SHP_1378SHP_1378SHP_3204SHP_70...  
Prod_14  SHP_7252SHP_6892SHP_6858SHP_4132SHP_304SHP_615...  
Prod_15  SHP_6228SHP_7024SHP_7299SHP_7659SHP_346SHP_189...  
Prod_16  SHP_7609SHP_4112SHP_7663SHP_5175SHP_5771SHP_66...  
Prod_17  SHP_7664SHP_7042SHP_7287SHP_7306SHP_7671SHP_16...  
Prod_2   SHP_6615SHP_7022SHP_7032SHP_6545SHP_6322SHP_64...  
Prod_3   SHP_3525SHP_7033SHP_7310SHP_7288SHP_166SHP_339...  
Prod_4   SHP_7610SHP_6593SHP_3527SHP_6651SHP_6531SHP_63...  
Prod_5   SHP_3114SHP_1377SHP_3367SHP_7040SHP_6490SHP_65...  
Prod_6   SHP_7625SHP_7608SHP_6593SHP_2637SHP_6171SHP_13...  
Prod_7   SHP_1378SHP_3526SHP_7041SHP_2261SHP_1993SHP_25...  
Prod_8   SHP_6328SHP_5892SHP_341SHP_164SHP_7504SHP_2078...  
Prod_9   SHP_3122SHP_3300SHP_3203SHP_182SHP_6073SHP_373...

In [248]:
df['isProfitable']=df['Profit'].apply(lambda x: 'profitable' if x>0 else 'not profitable')

In [249]:
df.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin    isProfitable  
0   -30.51           3.60                 0.56  not profitable  
1     4.56           0.93                 0.54      profitable  
2  1148.90           2.50                 0.59      profitable  
3   729.34          14.30                 0.37      profitable  
4  1219.87          26.30                 0.38      profitable